# Generated by Django 4.2.3 on 2023-07-16 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('prod_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prod_name', models.CharField(blank=True, max_length=100, null=True)),
                ('prod_code', models.CharField(blank=True, max_length=25, null=True)),
                ('prod_date', models.DateField(blank=True, null=True)),
                ('prod_age', models.BigIntegerField(blank=True, null=True)),
                ('prod_active', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'product_details',
                'managed': False,
            },
        ),
    ]
